
//TODO: split Test script descriptoer on every TestScript

//ReadAndCompare descriptor
TEST_SCRIPT_DESC_STRAT(ReadAndCompare)
TEST_SCRIPT_DESC_COMMAND(READ)
TEST_SCRIPT_DESC_COMMAND(READ)
TEST_SCRIPT_DESC_COMMAND(READ)
TEST_SCRIPT_DESC_END()

#undef TEST_SCRIPT_DESC_STRAT()
#undef TEST_SCRIPT_DESC_COMMAND()
#undef TEST_SCRIPT_DESC_END()
